### PR TITLE
Feature/lp49 posts

### PR DESCRIPTION
**Pull request by juanislas77**
Create the card for user post using compose

### CODE REVIEW

**Comment by melissaquezada94** [comment]
Hi Juan,
Would be nice that when you create the PR, you add the name of the task, the task's link to navigate to Jira and a brief overview of what was added, deleted or updated in the code. So it's easier to do the code review, please.

**Comment by melissaquezada94** [comment]
Another observation it's that you could do a squash in your commits to have just one commit per PR.

**Comment by juanislas77** [comment]
image 
_Preview of LpPostCard in an Android 13 Device_

LP-49 Posts
https://devaptivist.atlassian.net/browse/LP-49

Hi Melissa, sorry, I'm adding the info you requested

**Comment by juanislas77** [comment]
Aba

**Pull request closed without merging**
